### ISSUE TITLE
missing repo_name entry

### ISSUE THREAD

**Issue by theappleman** [bencord0/portage-overlay#1]
WARNING: One or more repositories have missing repo_name entries:
    
        /usr/local/bencord0-overlay/profiles/repo_name
    
NOTE: Each repo_name entry should be a plain text file containing a
unique name for the repository on the first line.

**Comment by bencord0** [comment]
Fixed in https://github.com/bencord0/portage-overlay/commit/5cb540904284d285554042957f995dda556f3103
